//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kucni_poslovi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SfResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SfResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kucni_poslovi.Resources.SfResources", typeof(SfResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string Uploader_Abort {
            get {
                return ResourceManager.GetString("Uploader_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nadji sliku.
        /// </summary>
        public static string Uploader_Browse {
            get {
                return ResourceManager.GetString("Uploader_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poništi.
        /// </summary>
        public static string Uploader_Cancel {
            get {
                return ResourceManager.GetString("Uploader_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        public static string Uploader_Clear {
            get {
                return ResourceManager.GetString("Uploader_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obirši fajl.
        /// </summary>
        public static string Uploader_Delete {
            get {
                return ResourceManager.GetString("Uploader_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ili prevucite sliku ovde.
        /// </summary>
        public static string Uploader_DropFilesHint {
            get {
                return ResourceManager.GetString("Uploader_DropFilesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otpremanje poništeno.
        /// </summary>
        public static string Uploader_FileUploadCancel {
            get {
                return ResourceManager.GetString("Uploader_FileUploadCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otpremanje.
        /// </summary>
        public static string Uploader_InProgress {
            get {
                return ResourceManager.GetString("Uploader_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka ovog tipa nije dozvoljena.
        /// </summary>
        public static string Uploader_InvalidFileType {
            get {
                return ResourceManager.GetString("Uploader_InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka je previše velika.
        /// </summary>
        public static string Uploader_InvalidMaxFileSize {
            get {
                return ResourceManager.GetString("Uploader_InvalidMaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datoteka je previše mala.
        /// </summary>
        public static string Uploader_invalidMinFileSize {
            get {
                return ResourceManager.GetString("Uploader_invalidMinFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pauza.
        /// </summary>
        public static string Uploader_Pause {
            get {
                return ResourceManager.GetString("Uploader_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otpremanje datoteke pauzirano.
        /// </summary>
        public static string Uploader_PauseUpload {
            get {
                return ResourceManager.GetString("Uploader_PauseUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to upload.
        /// </summary>
        public static string Uploader_ReadyToUploadMessage {
            get {
                return ResourceManager.GetString("Uploader_ReadyToUploadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukloni.
        /// </summary>
        public static string Uploader_Remove {
            get {
                return ResourceManager.GetString("Uploader_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nije moguće ukloniti datoteku.
        /// </summary>
        public static string Uploader_RemovedFailedMessage {
            get {
                return ResourceManager.GetString("Uploader_RemovedFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspešno uklonjena datoteka.
        /// </summary>
        public static string Uploader_RemovedSuccessMessage {
            get {
                return ResourceManager.GetString("Uploader_RemovedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastavi.
        /// </summary>
        public static string Uploader_Resume {
            get {
                return ResourceManager.GetString("Uploader_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probaj opet.
        /// </summary>
        public static string Uploader_Retry {
            get {
                return ResourceManager.GetString("Uploader_Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otpremi.
        /// </summary>
        public static string Uploader_Upload {
            get {
                return ResourceManager.GetString("Uploader_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otpremanje nije uspelo.
        /// </summary>
        public static string Uploader_UploadFailedMessage {
            get {
                return ResourceManager.GetString("Uploader_UploadFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otpremanje uspešno.
        /// </summary>
        public static string Uploader_UploadSuccessMessage {
            get {
                return ResourceManager.GetString("Uploader_UploadSuccessMessage", resourceCulture);
            }
        }
    }
}
